### ISSUE TITLE
What's the 'video.srt'

### ISSUE THREAD

**Issue by Tylerjoe** [BitFloyd/deepsbd#1]
Thanks for your good work,
But I have a question about the video_srt_path = 'video.srt'.
what's the .srt file?
Thanks!

**Comment by BitFloyd** [comment]
Hi,
The .srt file is a subtitle file if you have one.
You can pass an empty text file if you don't need subtitles.
I'll add a switch for that in the code when I get time where you can pass None and everything falls through without subs.
